
const S=[...document.querySelectorAll('.stage')],F=document.querySelector('.fill'),PT=document.querySelector('#pt'),PL=document.querySelector('#pl');let i=0,done=false,buddy={n:'Nova',r:'Strategic Guide',e:'🧭'};const labels=['Launch Briefing','Choose Your Buddy','Mission Briefing','Interactive LAB','Innovation Check','Reflection','Debrief','Achievement'];
function show(n){i=Math.max(0,Math.min(7,n));S.forEach((x,k)=>x.classList.toggle('active',k===i));F.style.width=((i+1)/8*100)+'%';PT.textContent=(i+1)+' of 8';PL.textContent=labels[i];scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.next').forEach(b=>b.onclick=()=>show(i+1));document.querySelectorAll('.prev').forEach(b=>b.onclick=()=>show(i-1));
const name=document.querySelector('#name'),cb=document.querySelector('#confirmBuddy');document.querySelectorAll('.buddyopt').forEach(b=>b.onclick=()=>{document.querySelectorAll('.buddyopt').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');buddy={n:b.dataset.n,r:b.dataset.r,e:b.dataset.e};document.querySelectorAll('.bicon').forEach(x=>x.textContent=buddy.e);document.querySelectorAll('.bname').forEach(x=>x.textContent=buddy.n);cb.disabled=name.value.trim().length<2});name.oninput=()=>cb.disabled=!(document.querySelector('.buddyopt.sel')&&name.value.trim().length>1);
function win(msg){done=true;document.querySelector('#mnext').disabled=false;let f=document.querySelector('#mf');f.className='feedback ok';f.textContent=msg}
const type=document.body.dataset.type;
if(type==='code'){document.querySelector('#run').onclick=()=>{let c=document.querySelector('#code').value,o=document.querySelector('#out');if(c.includes('READY')&&c.includes('print')){o.textContent='Signal restored!\nNOVA connection: ONLINE';win('Mission complete. Your condition restored the signal.')}else{o.textContent='Keep searching...\nHint: include READY and print.'}}}
if(type==='robot'){let cmds=[];const d=document.querySelector('#cmds');document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{cmds.push(b.dataset.c);d.textContent='Sequence: '+cmds.join(' → ')});document.querySelector('#clear').onclick=()=>{cmds=[];d.textContent='Sequence: —'};document.querySelector('#launch').onclick=()=>{if(cmds.filter(x=>x==='F').length>=3&&cmds.includes('R')){document.querySelector('#rover').textContent='🤖 ➜ ➜ ➜ 🛟';win('Route confirmed. The rover reached the rescue module.')}else document.querySelector('#rover').textContent='Route incomplete. Try 3 Forward commands and 1 Right turn.'}}
if(type==='iot'){const th=document.querySelector('#th'),tv=document.querySelector('#tv');th.oninput=()=>tv.textContent=th.value;document.querySelector('#test').onclick=()=>{if(document.querySelector('#auto').checked&&+th.value<30){document.querySelector('#temp').textContent='27°C';document.querySelector('#fan').textContent='🌀 ACTIVE';win('Automation protected the greenhouse.')}else document.querySelector('#fan').textContent='Set threshold below 30°C and activate automation.'}}
document.querySelectorAll('.option').forEach(o=>o.onclick=()=>{document.querySelectorAll('.option').forEach(x=>x.classList.remove('good'));if(o.dataset.ok==='1'){o.classList.add('good');document.querySelector('#qnext').disabled=false;document.querySelector('#qf').textContent='Correct. You explained how the system works.'}else document.querySelector('#qf').textContent='Try again. Choose the answer that explains the system.'});
const ref=document.querySelector('#ref'),rn=document.querySelector('#rnext');ref.oninput=()=>rn.disabled=ref.value.trim().length<12;document.querySelector('#claim').onclick=()=>{document.querySelector('#finalName').textContent=name.value.trim()||'Explorer';document.querySelector('#finalBuddy').textContent=buddy.n;show(7)};document.querySelector('#restart').onclick=()=>location.reload();document.querySelector('#print').onclick=()=>print();
